import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import toastr from 'toastr';
import 'toastr/build/toastr.min.css';

toastr.options.timeOut = 2000;

const Home: NextPage = () => {
  const [input, setInput] = useState('');
  const [iframeUrl, setIframeUrl] = useState('');

  const iframeCode = `<iframe src="${iframeUrl}" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>`;

  const handleGenerateLink = () => {
    if (!input.startsWith('https://www.bilibili.com/video/BV')) {
      toastr.error('目前仅支持以 https://www.bilibili.com/video/BV 开头的地址');
      return;
    }
    setIframeUrl(`${window.origin}/player?url=${encodeURIComponent(input)}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Paw Bilibili player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Paw Bilibili Player</h1>
        <h3>
          因为 bilibili 的iframe 播放器过于简陋，因此我帮阿B重新做了一个播放器
        </h3>

        <div>
          <input
            className={styles.input}
            placeholder="请在此输入B站链接"
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />
          <div className={styles.button} onClick={handleGenerateLink}>
            生成链接
          </div>
        </div>
        {!iframeUrl ? (
          <p>
            例:{' '}
            <a
              href="https://www.bilibili.com/video/BV1ZF411g7EZ"
              target="_blank"
              rel="noreferrer"
            >
              https://www.bilibili.com/video/BV1ZF411g7EZ
            </a>
          </p>
        ) : (
          <div className={styles.player}>
            <iframe
              className={styles.playerIframe}
              src={iframeUrl}
              frameBorder="0"
              scrolling="0"
            ></iframe>

            <p>
              嵌入代码: <input className={styles.input} value={iframeCode} />
            </p>
          </div>
        )}
      </main>

      <div className={styles.github}>
        <p>注: 本项目完全开源免费</p>
        <p>
          如果你喜欢这个项目, 请给它一个大大的赞，您的支持就是我开源最大的动力
        </p>
        <iframe
          src="https://ghbtns.com/github-btn.html?user=msgbyte&repo=paw-bilibili-player&type=star&count=true&size=large"
          frameBorder="0"
          scrolling="0"
          width="170"
          height="30"
          title="GitHub"
        ></iframe>
      </div>

      <footer className={styles.footer}>
        Powered by <a href="http://moonrailgun.com">moonrailgun</a> with ❤
      </footer>
    </div>
  );
};

export default Home;
